import { hydrogenRoutes } from '@shopify/hydrogen';
import { route, index, type RouteConfig } from '@react-router/dev/routes';

export default hydrogenRoutes([
  index('routes/_index.tsx'),
  route('ar', 'routes/ar._index.tsx'),
  route('ar/*', 'routes/ar.$.tsx'),
  route('cart', 'routes/cart.tsx'),
  route('cart.js', 'routes/cart[.]js.tsx'),
  route('apps/loggedincustomer', 'routes/apps.loggedincustomer.tsx'),
  route('search', 'routes/search.tsx'),
  route('collections/:handle', 'routes/collections.$handle.tsx'),
  route('blogs/all', 'routes/blogs.all.tsx'),
  route('blogs/:handle', 'routes/blogs.$handle.tsx'),
  route('blogs/:blogHandle/:articleHandle', 'routes/blogs.$blogHandle.$articleHandle.tsx'),
  route('products/:handle', 'routes/products.$handle.tsx'),
  route('api/reviews/store', 'routes/api.reviews.store.tsx'),
  route('api/reviews/:handle', 'routes/api.reviews.$handle.tsx'),
  route('api/selling-plans/:handle', 'routes/api.selling-plans.$handle.tsx'),
  route('api/globo-options/:productId', 'routes/api.globo-options.$productId.tsx'),
  route('api/back-in-stock', 'routes/api.back-in-stock.tsx'),
  route('pages/customer-reviews', 'routes/pages.customer-reviews.tsx'),
  route('pages/contact-us', 'routes/pages.contact.tsx'),
  route('pages/refund-exchange', 'routes/pages.refund-exchange.tsx'),
  route('pages/rewards', 'routes/pages.rewards.tsx'),
  route('pages/mls-rewards', 'routes/pages.mls-rewards.tsx'),
  route('pages/all-blog', 'routes/pages.all-blog.tsx'),
  route('pages/refer-a-friend', 'routes/pages.refer-a-friend.tsx'),
  route('pages/faqs', 'routes/pages.faqs.tsx'),
  route('pages/mls-gourmet', 'routes/pages.mls-gourmet.tsx'),
  route('pages/our-story-new', 'routes/pages.our-story-new.tsx'),
  route('pages/mls-affiliate', 'routes/pages.mls-affiliate.tsx'),
  route('pages/delivery-info', 'routes/pages.delivery-info.tsx'),
  route('pages/subscription-policy', 'routes/pages.subscription-policy.tsx'),
  route('pages/subscriptions', 'routes/pages.subscriptions.tsx'),
  route('pages/subscription', 'routes/pages.subscription.tsx'),
  route('pages/:handle', 'routes/pages.$handle.tsx'),
  route('account', 'routes/account.tsx', [
    index('routes/account._index.tsx'),
    route('authorize', 'routes/account_.authorize.tsx'),
    route('logout', 'routes/account_.logout.tsx'),
  ]),
]) satisfies RouteConfig;
