// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/cart": {
    params: {};
  };
  "/search": {
    params: {};
  };
  "/collections/:handle": {
    params: {
      "handle": string;
    };
  };
  "/products/:handle": {
    params: {
      "handle": string;
    };
  };
  "/pages/:handle": {
    params: {
      "handle": string;
    };
  };
  "/api/reviews/:handle": {
    params: {
      "handle": string;
    };
  };
  "/api/selling-plans/:handle": {
    params: {
      "handle": string;
    };
  };
  "/account": {
    params: {};
  };
  "/account/authorize": {
    params: {};
  };
  "/account/logout": {
    params: {};
  };
  "/graphiql": {
    params: {};
  };
  "/subrequest-profiler": {
    params: {};
  };
  "/.well-known/appspecific/com.chrome.devtools.json": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/cart" | "/search" | "/collections/:handle" | "/products/:handle" | "/pages/:handle" | "/api/reviews/:handle" | "/api/selling-plans/:handle" | "/account" | "/account/authorize" | "/account/logout" | "/graphiql" | "/subrequest-profiler" | "/.well-known/appspecific/com.chrome.devtools.json";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/cart.tsx": {
    id: "routes/cart";
    page: "/cart";
  };
  "routes/search.tsx": {
    id: "routes/search";
    page: "/search";
  };
  "routes/collections.$handle.tsx": {
    id: "routes/collections.$handle";
    page: "/collections/:handle";
  };
  "routes/products.$handle.tsx": {
    id: "routes/products.$handle";
    page: "/products/:handle";
  };
  "routes/pages.$handle.tsx": {
    id: "routes/pages.$handle";
    page: "/pages/:handle";
  };
  "routes/api.reviews.$handle.tsx": {
    id: "routes/api.reviews.$handle";
    page: "/api/reviews/:handle";
  };
  "routes/api.selling-plans.$handle.tsx": {
    id: "routes/api.selling-plans.$handle";
    page: "/api/selling-plans/:handle";
  };
  "routes/account.tsx": {
    id: "routes/account";
    page: "/account" | "/account/authorize" | "/account/logout";
  };
  "routes/account._index.tsx": {
    id: "routes/account._index";
    page: "/account";
  };
  "routes/account_.authorize.tsx": {
    id: "routes/account_.authorize";
    page: "/account/authorize";
  };
  "routes/account_.logout.tsx": {
    id: "routes/account_.logout";
    page: "/account/logout";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/layout.jsx": {
    id: "/Users/laptechpk/Downloads/MLS Hyd/Hydrogen-Lovable/hydrogen/node_modules/@shopify/hydrogen/dist/vite/virtual-routes/layout";
    page: "/graphiql" | "/subrequest-profiler" | "/.well-known/appspecific/com.chrome.devtools.json" | "/";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/graphiql.jsx": {
    id: "vite/virtual-routes/routes/graphiql";
    page: "/graphiql";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/subrequest-profiler.jsx": {
    id: "vite/virtual-routes/routes/subrequest-profiler";
    page: "/subrequest-profiler";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/[.]well-known.appspecific.com[.]chrome[.]devtools[.]json.jsx": {
    id: "vite/virtual-routes/routes/[.]well-known.appspecific.com[.]chrome[.]devtools[.]json";
    page: "/.well-known/appspecific/com.chrome.devtools.json";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/index.jsx": {
    id: "vite/virtual-routes/routes/index";
    page: "/";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/cart": typeof import("./app/routes/cart.tsx");
  "routes/search": typeof import("./app/routes/search.tsx");
  "routes/collections.$handle": typeof import("./app/routes/collections.$handle.tsx");
  "routes/products.$handle": typeof import("./app/routes/products.$handle.tsx");
  "routes/pages.$handle": typeof import("./app/routes/pages.$handle.tsx");
  "routes/api.reviews.$handle": typeof import("./app/routes/api.reviews.$handle.tsx");
  "routes/api.selling-plans.$handle": typeof import("./app/routes/api.selling-plans.$handle.tsx");
  "routes/account": typeof import("./app/routes/account.tsx");
  "routes/account._index": typeof import("./app/routes/account._index.tsx");
  "routes/account_.authorize": typeof import("./app/routes/account_.authorize.tsx");
  "routes/account_.logout": typeof import("./app/routes/account_.logout.tsx");
  "/Users/laptechpk/Downloads/MLS Hyd/Hydrogen-Lovable/hydrogen/node_modules/@shopify/hydrogen/dist/vite/virtual-routes/layout": unknown;
  "vite/virtual-routes/routes/graphiql": unknown;
  "vite/virtual-routes/routes/subrequest-profiler": unknown;
  "vite/virtual-routes/routes/[.]well-known.appspecific.com[.]chrome[.]devtools[.]json": unknown;
  "vite/virtual-routes/routes/index": unknown;
};